name: build docker image CI

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry-intl.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Get Version
        run: |
          version=$(awk '$1=="manifest.version"{print $3}' nextflow.config | sed 's/"//g; s/v//')
          echo "VERSION=$version" >> "$GITHUB_ENV"
        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            obenno/starscope_scrnaseq_env:latest
            obenno/starscope_scrnaseq_env:${{ env.VERSION }}
            registry-intl.cn-hangzhou.aliyuncs.com/thunderbio/starscope_scrnaseq_env:latest
            registry-intl.cn-hangzhou.aliyuncs.com/thunderbio/starscope_scrnaseq_env:${{ env.VERSION }}
          cache-from: type=registry,ref=obenno/starscope_scrnaseq_env:latest
          cache-to: type=inline
